micronaut:
  server:
    cors:
      enabled: true
  application:
    name: APIParking
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

xparc:
  host: https://staging.xparc.eu/
  host1: https://xparc.eu
  service:
    path: SmartParkingWebServiceDemo/
    path1: /restwebdemo/5E2AC0438FE65CEA/
  version: v1/
  ticket:
    getPath: Ticket/
    method: requestTicket/
  user:
    registryPath: users
    getPath: users/